ARG NODE_JS_IMAGE_VERSION=20-alpine

FROM node:${NODE_JS_IMAGE_VERSION} AS build

ADD . /project
WORKDIR /project

RUN npm ci

RUN npm run build

FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html

COPY --from=build /project/dist .

RUN rm /etc/nginx/conf.d/default.conf

COPY docker/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

